### ISSUE TITLE
Any reason for this plugin not be listed in official obsidian community plugins list?

### ISSUE THREAD

**Issue by marco7m** [davidvdev/obsidian-note-timer#8]
This is the exact plugin I was looking for! Hope more people find it.

**Comment by davidvdev** [comment]
I can look into submitting it again.
 
I originally developed it for the plugin contest back in October 2021, but haven't put much active development into it since then. The generous contributions from @Pr0dt0s are the main reason this plugin works as well as it does!

I'm glad this works for you! I built it while I was practicing interviewing and other presentation things, but I've needed it less and less over the years, so I'm usually the last user to notice if things aren't working properly. 😅
